spring.application.name=bank-app
server.port=8080

# --- Database (MySQL) ---
# Modifica username/password con quelli del tuo server MySQL locale.
spring.datasource.url=jdbc:mysql://localhost:3306/bankapp?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
app.jwt.secret=GQAa9LdDILnDsLFlX9+Hphm0tE19mf9z7RVeyQFBsHwCL4h2FVOvIVDoIjXuz/Dh
app.jwt.expiration-ms=3600000

# --- Codici OTP / token di conferma ---
app.otp.expiration-minutes=5
app.confirmation-token.expiration-hours=24
app.base-url=http://localhost:8080
